


spring:
  application:
    name: clould-config-center   #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luckylifes/springcloud-config.git  #GitHub上仓库地址
          #搜索目录
          search-paths:
            - springcloud-config
          username: wangjia123
          password: slh110711
          default-label: master
  #rabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 3344


#rabbitMQ配置 暴露bus刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"








eureka:
  client:
    # 表示将自己注册进去向服务注册中心eureka-server
    register-with-eureka: true
    #是否从eureka-server抓取已有的注册信息 默认为true 单节点无所谓 集群必须设置true才能配合ribbon使用负载均衡
    fetchRegistry: true

    service-url:
      defaultZone: http://localhost:7001/eureka/ #单机
      #defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka  #集群版
  instance:
    instance-id: clould-config-center
    prefer-ip-address: true  #访问路径可以显示IP地址

#    #Eureka客户端向服务端发送心跳的时间 单位秒 默认30
#    lease-renewal-interval-in-seconds: 30
#    #Eureka服务端在接收到最后一次心跳后等待时间上线 单位 秒  默认是90秒 超时就删除服务
#    lease-expiration-duration-in-seconds: 90




